favicon: /favicon.png
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

logo:

article:
  readtime: true
  highlight: atom-one-light

search:
  type: insight

share:
  type: sharethis
  install_url: //platform-api.sharethis.com/js/sharethis.js#property=5ad47e52d0b9d300137e38f0&product=inline-share-buttons

comment:
  type: disqus
  shortname: dengcb

plugins:
  mathjax: true
  gallery: true
  google-analytics:
    tracking_id:

navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/dengcb

footer_links: